name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform -chdir= .github/azure-three-tier-app/infrastructure init

      - name: Terraform Plan
        run: terraform -chdir= .github/azure-three-tier-app/infrastructure plan

      - name: Terraform Apply
        run: terraform -chdir= .github/azure-three-tier-app/infrastructure apply -auto-approve